version: '3'
services:
  booking-service:
    build: ./services/bookings
    ports:
      - "8080:8080"
    environment:
      - DYNAMO_ENDPOINT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    links:
      - agent-service
      - storage
  agent-service: 
    image: "diendang/agents-svc"
    ports:
      - "8081:8081"
      - "9091:9091"
  storage:
    image: "amazon/dynamodb-local"
    ports:
     - "8000:8000"
  awscli:
    image: "governmentpaas/awscli"
    links:
      - storage
  ddbadmin:
    image: "aaronshaf/dynamodb-admin"
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
