// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/agents.proto

package bootcamp_srv_agents

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NearbyAgentRequest struct {
	Location             *Location `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *NearbyAgentRequest) Reset()         { *m = NearbyAgentRequest{} }
func (m *NearbyAgentRequest) String() string { return proto.CompactTextString(m) }
func (*NearbyAgentRequest) ProtoMessage()    {}
func (*NearbyAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_c46276eb809031eb, []int{0}
}
func (m *NearbyAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NearbyAgentRequest.Unmarshal(m, b)
}
func (m *NearbyAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NearbyAgentRequest.Marshal(b, m, deterministic)
}
func (dst *NearbyAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NearbyAgentRequest.Merge(dst, src)
}
func (m *NearbyAgentRequest) XXX_Size() int {
	return xxx_messageInfo_NearbyAgentRequest.Size(m)
}
func (m *NearbyAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NearbyAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NearbyAgentRequest proto.InternalMessageInfo

func (m *NearbyAgentRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Location struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_c46276eb809031eb, []int{1}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type NearbyAgentResponse struct {
	Agent                *AgentInfo `protobuf:"bytes,1,opt,name=agent" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *NearbyAgentResponse) Reset()         { *m = NearbyAgentResponse{} }
func (m *NearbyAgentResponse) String() string { return proto.CompactTextString(m) }
func (*NearbyAgentResponse) ProtoMessage()    {}
func (*NearbyAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_c46276eb809031eb, []int{2}
}
func (m *NearbyAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NearbyAgentResponse.Unmarshal(m, b)
}
func (m *NearbyAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NearbyAgentResponse.Marshal(b, m, deterministic)
}
func (dst *NearbyAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NearbyAgentResponse.Merge(dst, src)
}
func (m *NearbyAgentResponse) XXX_Size() int {
	return xxx_messageInfo_NearbyAgentResponse.Size(m)
}
func (m *NearbyAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NearbyAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NearbyAgentResponse proto.InternalMessageInfo

func (m *NearbyAgentResponse) GetAgent() *AgentInfo {
	if m != nil {
		return m.Agent
	}
	return nil
}

type AgentInfo struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentInfo) Reset()         { *m = AgentInfo{} }
func (m *AgentInfo) String() string { return proto.CompactTextString(m) }
func (*AgentInfo) ProtoMessage()    {}
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_agents_c46276eb809031eb, []int{3}
}
func (m *AgentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInfo.Unmarshal(m, b)
}
func (m *AgentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInfo.Marshal(b, m, deterministic)
}
func (dst *AgentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInfo.Merge(dst, src)
}
func (m *AgentInfo) XXX_Size() int {
	return xxx_messageInfo_AgentInfo.Size(m)
}
func (m *AgentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInfo proto.InternalMessageInfo

func (m *AgentInfo) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *AgentInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*NearbyAgentRequest)(nil), "bootcamp.srv.agents.NearbyAgentRequest")
	proto.RegisterType((*Location)(nil), "bootcamp.srv.agents.Location")
	proto.RegisterType((*NearbyAgentResponse)(nil), "bootcamp.srv.agents.NearbyAgentResponse")
	proto.RegisterType((*AgentInfo)(nil), "bootcamp.srv.agents.AgentInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AgentService service

type AgentServiceClient interface {
	NearbyAgent(ctx context.Context, in *NearbyAgentRequest, opts ...grpc.CallOption) (*NearbyAgentResponse, error)
}

type agentServiceClient struct {
	cc *grpc.ClientConn
}

func NewAgentServiceClient(cc *grpc.ClientConn) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) NearbyAgent(ctx context.Context, in *NearbyAgentRequest, opts ...grpc.CallOption) (*NearbyAgentResponse, error) {
	out := new(NearbyAgentResponse)
	err := grpc.Invoke(ctx, "/bootcamp.srv.agents.AgentService/NearbyAgent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AgentService service

type AgentServiceServer interface {
	NearbyAgent(context.Context, *NearbyAgentRequest) (*NearbyAgentResponse, error)
}

func RegisterAgentServiceServer(s *grpc.Server, srv AgentServiceServer) {
	s.RegisterService(&_AgentService_serviceDesc, srv)
}

func _AgentService_NearbyAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NearbyAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).NearbyAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bootcamp.srv.agents.AgentService/NearbyAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).NearbyAgent(ctx, req.(*NearbyAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bootcamp.srv.agents.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NearbyAgent",
			Handler:    _AgentService_NearbyAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/agents.proto",
}

func init() { proto.RegisterFile("pb/agents.proto", fileDescriptor_agents_c46276eb809031eb) }

var fileDescriptor_agents_c46276eb809031eb = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0x49, 0xf1, 0x4f, 0x32, 0x15, 0x0a, 0x53, 0x04, 0x0d, 0x55, 0x64, 0x2f, 0x16, 0x0f,
	0x09, 0x56, 0x2f, 0xf6, 0x26, 0x78, 0x29, 0x8a, 0xc2, 0xfa, 0x00, 0xb2, 0x49, 0xd6, 0x10, 0x48,
	0x77, 0x62, 0xb2, 0x8d, 0x78, 0xf5, 0xe2, 0x03, 0xf8, 0x68, 0xbe, 0x82, 0x0f, 0x22, 0x4e, 0x62,
	0x54, 0x0c, 0x78, 0xcb, 0xfc, 0xe6, 0x9b, 0xc9, 0xb7, 0xbb, 0x30, 0x2a, 0xa2, 0x50, 0xa5, 0xda,
	0xd8, 0x2a, 0x28, 0x4a, 0xb2, 0x84, 0xe3, 0x88, 0xc8, 0xc6, 0x6a, 0x59, 0x04, 0x55, 0x59, 0x07,
	0x4d, 0xcb, 0x9f, 0xa4, 0x44, 0x69, 0xae, 0x43, 0x55, 0x64, 0xa1, 0x32, 0x86, 0xac, 0xb2, 0x19,
	0x99, 0x76, 0x44, 0xdc, 0x00, 0x5e, 0x6b, 0x55, 0x46, 0x4f, 0xe7, 0x9f, 0xb4, 0xd4, 0x0f, 0x2b,
	0x5d, 0x59, 0x3c, 0x03, 0x37, 0xa7, 0x98, 0xc1, 0x1d, 0xe7, 0xc0, 0x99, 0x0e, 0x67, 0x7b, 0x41,
	0xcf, 0xee, 0xe0, 0xaa, 0x85, 0x64, 0x87, 0x8b, 0x0b, 0x70, 0xbf, 0x52, 0xf4, 0xc1, 0xcd, 0x95,
	0xcd, 0xec, 0x2a, 0xd1, 0xbc, 0xc6, 0x91, 0x5d, 0x8d, 0x13, 0xf0, 0x72, 0x32, 0x69, 0xd3, 0x1c,
	0x70, 0xf3, 0x3b, 0x10, 0x97, 0x30, 0xfe, 0xa5, 0x55, 0x15, 0x64, 0x2a, 0x8d, 0xa7, 0xb0, 0xce,
	0x7f, 0x6e, 0xa5, 0xf6, 0x7b, 0xa5, 0x78, 0x64, 0x61, 0xee, 0x49, 0x36, 0xb0, 0x98, 0x83, 0xd7,
	0x65, 0xb8, 0x0b, 0x2e, 0xa7, 0x77, 0x59, 0xc2, 0x5b, 0x3c, 0xb9, 0xc9, 0xf5, 0x22, 0x41, 0x84,
	0x35, 0xa3, 0x96, 0x8d, 0x8d, 0x27, 0xf9, 0x7b, 0xf6, 0xe2, 0xc0, 0x16, 0x0f, 0xdf, 0xea, 0xb2,
	0xce, 0x62, 0x8d, 0x8f, 0x30, 0xfc, 0x61, 0x86, 0x87, 0xbd, 0x0a, 0x7f, 0xaf, 0xd4, 0x9f, 0xfe,
	0x0f, 0x36, 0x87, 0x14, 0xdb, 0xcf, 0x6f, 0xef, 0xaf, 0x83, 0x91, 0x80, 0xb0, 0x3e, 0x0e, 0x0d,
	0x03, 0x73, 0xe7, 0x28, 0xda, 0xe0, 0x07, 0x3b, 0xf9, 0x08, 0x00, 0x00, 0xff, 0xff, 0xae, 0x84,
	0xa5, 0x75, 0xf6, 0x01, 0x00, 0x00,
}
