// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/bookings.proto

package bootcamp_srv_bookings

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateBookingRequest struct {
	UserId               string    `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Location             *Location `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateBookingRequest) Reset()         { *m = CreateBookingRequest{} }
func (m *CreateBookingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookingRequest) ProtoMessage()    {}
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_70398a3aeb026b0d, []int{0}
}

func (m *CreateBookingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookingRequest.Unmarshal(m, b)
}
func (m *CreateBookingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookingRequest.Marshal(b, m, deterministic)
}
func (m *CreateBookingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookingRequest.Merge(m, src)
}
func (m *CreateBookingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookingRequest.Size(m)
}
func (m *CreateBookingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookingRequest proto.InternalMessageInfo

func (m *CreateBookingRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateBookingRequest) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type CreateBookingResponse struct {
	BookingId            int32    `protobuf:"varint,1,opt,name=bookingId,proto3" json:"bookingId,omitempty"`
	Agent                *Agent   `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookingResponse) Reset()         { *m = CreateBookingResponse{} }
func (m *CreateBookingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBookingResponse) ProtoMessage()    {}
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_70398a3aeb026b0d, []int{1}
}

func (m *CreateBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookingResponse.Unmarshal(m, b)
}
func (m *CreateBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookingResponse.Marshal(b, m, deterministic)
}
func (m *CreateBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookingResponse.Merge(m, src)
}
func (m *CreateBookingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBookingResponse.Size(m)
}
func (m *CreateBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookingResponse proto.InternalMessageInfo

func (m *CreateBookingResponse) GetBookingId() int32 {
	if m != nil {
		return m.BookingId
	}
	return 0
}

func (m *CreateBookingResponse) GetAgent() *Agent {
	if m != nil {
		return m.Agent
	}
	return nil
}

// Agent Type
type Agent struct {
	AgentId              string   `protobuf:"bytes,1,opt,name=agentId,proto3" json:"agentId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Vehicle              string   `protobuf:"bytes,3,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Rating               int32    `protobuf:"varint,4,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_70398a3aeb026b0d, []int{2}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetAgentId() string {
	if m != nil {
		return m.AgentId
	}
	return ""
}

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Agent) GetVehicle() string {
	if m != nil {
		return m.Vehicle
	}
	return ""
}

func (m *Agent) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

// Location Type
type Location struct {
	Longitude            float64  `protobuf:"fixed64,1,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_70398a3aeb026b0d, []int{3}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateBookingRequest)(nil), "bootcamp.srv.bookings.CreateBookingRequest")
	proto.RegisterType((*CreateBookingResponse)(nil), "bootcamp.srv.bookings.CreateBookingResponse")
	proto.RegisterType((*Agent)(nil), "bootcamp.srv.bookings.Agent")
	proto.RegisterType((*Location)(nil), "bootcamp.srv.bookings.Location")
}

func init() { proto.RegisterFile("pb/bookings.proto", fileDescriptor_70398a3aeb026b0d) }

var fileDescriptor_70398a3aeb026b0d = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4e, 0xf2, 0x40,
	0x14, 0xc5, 0x53, 0x3e, 0xe0, 0x83, 0x6b, 0x34, 0x61, 0x22, 0xa4, 0x21, 0x4d, 0x24, 0x5d, 0x11,
	0x35, 0x6d, 0xc4, 0x9d, 0xae, 0xfc, 0xb3, 0x31, 0x61, 0x35, 0x3e, 0xc1, 0xb4, 0xdc, 0x8c, 0x13,
	0x60, 0x6e, 0x6d, 0x87, 0x3e, 0x80, 0x2b, 0xf7, 0x2e, 0x7d, 0x2c, 0x5f, 0xc1, 0x07, 0x31, 0x9d,
	0x0e, 0xa0, 0x06, 0x12, 0x77, 0x3d, 0xf7, 0xfe, 0xee, 0x9c, 0x9e, 0x3b, 0x03, 0xbd, 0x2c, 0x89,
	0x13, 0xa2, 0xb9, 0xd2, 0xb2, 0x88, 0xb2, 0x9c, 0x0c, 0xb1, 0x7e, 0x42, 0x64, 0x52, 0xb1, 0xcc,
	0xa2, 0x22, 0x2f, 0xa3, 0x75, 0x73, 0x18, 0x48, 0x22, 0xb9, 0xc0, 0x58, 0x64, 0x2a, 0x16, 0x5a,
	0x93, 0x11, 0x46, 0x91, 0x76, 0x43, 0xe1, 0x1c, 0x8e, 0xef, 0x72, 0x14, 0x06, 0x6f, 0x6b, 0x9e,
	0xe3, 0xf3, 0x0a, 0x0b, 0xc3, 0x06, 0xd0, 0x5e, 0x15, 0x98, 0x3f, 0xcc, 0x7c, 0x6f, 0xe4, 0x8d,
	0xbb, 0xdc, 0x29, 0x76, 0x0d, 0x9d, 0x05, 0xa5, 0xf6, 0x08, 0xbf, 0x31, 0xf2, 0xc6, 0x07, 0x93,
	0x93, 0x68, 0xa7, 0x6f, 0x34, 0x75, 0x18, 0xdf, 0x0c, 0x84, 0x0a, 0xfa, 0xbf, 0xcc, 0x8a, 0x8c,
	0x74, 0x81, 0x2c, 0x80, 0xae, 0x9b, 0x73, 0x86, 0x2d, 0xbe, 0x2d, 0xb0, 0x09, 0xb4, 0x84, 0x44,
	0x6d, 0x9c, 0x61, 0xb0, 0xc7, 0xf0, 0xa6, 0x62, 0x78, 0x8d, 0x86, 0x12, 0x5a, 0x56, 0x33, 0x1f,
	0xfe, 0xdb, 0xca, 0x26, 0xc9, 0x5a, 0x32, 0x06, 0x4d, 0x2d, 0x96, 0x68, 0x4f, 0xed, 0x72, 0xfb,
	0x5d, 0xd1, 0x25, 0x3e, 0xa9, 0x74, 0x81, 0xfe, 0xbf, 0x9a, 0x76, 0xb2, 0x5a, 0x48, 0x2e, 0x8c,
	0xd2, 0xd2, 0x6f, 0xda, 0xff, 0x73, 0x2a, 0xbc, 0x87, 0xce, 0x3a, 0x69, 0x15, 0x63, 0x4a, 0x5a,
	0x2a, 0xb3, 0x9a, 0xa1, 0x75, 0xf3, 0xf8, 0xb6, 0xc0, 0x86, 0xd0, 0x99, 0x0a, 0x53, 0x37, 0x1b,
	0xb6, 0xb9, 0xd1, 0x93, 0x77, 0x0f, 0x8e, 0xdc, 0x52, 0x1e, 0x31, 0x2f, 0x55, 0x8a, 0xec, 0xd5,
	0x83, 0xc3, 0x1f, 0xdb, 0x62, 0x67, 0x7b, 0x82, 0xef, 0xba, 0xc0, 0xe1, 0xf9, 0xdf, 0xe0, 0xfa,
	0x02, 0xc2, 0xe0, 0xe5, 0xe3, 0xf3, 0xad, 0x31, 0x08, 0x7b, 0x71, 0x79, 0x11, 0xa7, 0xdf, 0x91,
	0x2b, 0xef, 0x34, 0x69, 0xdb, 0xb7, 0x72, 0xf9, 0x15, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x59, 0xf8,
	0xc5, 0x75, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookingServiceClient is the client API for BookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookingServiceClient interface {
	CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*CreateBookingResponse, error)
}

type bookingServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookingServiceClient(cc *grpc.ClientConn) BookingServiceClient {
	return &bookingServiceClient{cc}
}

func (c *bookingServiceClient) CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*CreateBookingResponse, error) {
	out := new(CreateBookingResponse)
	err := c.cc.Invoke(ctx, "/bootcamp.srv.bookings.BookingService/CreateBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServiceServer is the server API for BookingService service.
type BookingServiceServer interface {
	CreateBooking(context.Context, *CreateBookingRequest) (*CreateBookingResponse, error)
}

// UnimplementedBookingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookingServiceServer struct {
}

func (*UnimplementedBookingServiceServer) CreateBooking(ctx context.Context, req *CreateBookingRequest) (*CreateBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBooking not implemented")
}

func RegisterBookingServiceServer(s *grpc.Server, srv BookingServiceServer) {
	s.RegisterService(&_BookingService_serviceDesc, srv)
}

func _BookingService_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bootcamp.srv.bookings.BookingService/CreateBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).CreateBooking(ctx, req.(*CreateBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bootcamp.srv.bookings.BookingService",
	HandlerType: (*BookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBooking",
			Handler:    _BookingService_CreateBooking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/bookings.proto",
}
